### PR TITLE
Update smufl to 1.2

### PR DESCRIPTION
**Pull request by mrtnnbr**

### CODE REVIEW

**Comment by uliska** [comment]
Thank you for the pull request. Three comments:

1. I can't really comment on them because that's not my field of knowledge. I suggest merging the pull request nevertheless.
2. Shouldn't the Bravura font be updated too?
3. This Pull request is a) on the `master` branch and b) contains two completely unrelated topics. I can deal with that but in the future you should create branches before adding commits.

I will incorporate the default stylesheet and wait with the other for a comment on Bravura

**Comment by mrtnnbr** [comment]
Hi Urs,

Regarding your comments:
1. The change to glyphnames.py should be pretty straightforward. The diff of the re-generated smufldata.ily is a bit unwieldy, but that would have been the case with the old script as well. On the other hand, possible future changes or additions to the glyph names will lead to much smaller and more localised diffs.

2. I didn't update the Bravura font mainly because I'm not fully convinced it needs to (or should) be in the repository in the first place. But I'm not very passionate of that either way.

3. That was my fault. I (wrongly) made the assumption that later commits wouldn't be added to existing pull requests. Plus, I'm still following the cloning-is-branching way of using DVCSs. 

Hope that clarifies things a bit,
Martin

**Comment by uliska** [comment]
@kierenmacmillan @tisimst 
Do you have an opinion o whether the Bravura font itself should be stored in this package/repository?

Of course it's redundant and could be replaced with a reference to its original location and download link. The argument for having it would be to keep it consistent with our wrapper package.

(as an aside: as long as LilyPond doesn't natively support SMuFL I think we should keep this compatibility layer around in addition to Abraham's converted font.

@mrtnnbr Should I add you to the repo as a contributor?

**Comment by tisimst** [comment]
I think it makes sense to add Bravura itself (as well as Bravura Text) because it is closely tied to the other SMuFL related files and it doesn't make sense to update one without updating the others.

**Comment by mrtnnbr** [comment]
Actually not as closely tied these days as at the time the SMuFL support was originally written. Now the SMuFL metadata is hosted at https://github.com/w3c/smufl while the Bravura font can be found at https://github.com/steinbergmedia/bravura . Of course, Bravura still is the reference implementation for SMuFL.

That means, strictly speaking glyphnames.json is independent of the Bravura font, as is smufldata.ily derived from it. That leaves definitions.ily, which is a mix of general support for SMuFL features and stylesheet for Bravura. I'd rather have this separated than use the current state as argument how the module should be organised.

Another point would be that one can checkout the repository to an appropriate location and the lilypond includes just work, while the font files would have to be copied to the lilypond installation directory in an additional step. And then we could just let the user decide, where to copy from...

Finally, on a more personal note, I'm always a bit sceptical about putting large binary blobs under source control. Back when I started out that was just a big no-no, and I somehow kept that attitude. Of course, the font files aren't that huge given current hard drives, but they already account for most of the repository's size. Keeping them in sync with the official releases would make that only more pronounced.

All this doesn't mean the font files have to go (and there definitely are arguments for keeping them), but I felt the decision isn't that clear-cut. And I'd just be more more comfortable with reaching a decision after considering possible objections (even if those are rejected).

**Comment by uliska** [comment]
I think I wouldn't take paragraphs 3-4 as strong arguments to remove the font files, but 1-2 *are*.

It's correct that the `smufl` adapter in this package is a *SMuFL* and not a *Bravura* adaptor. So I've added some tasks to #5 but can't look into that at the moment.

**Comment by tisimst** [comment]
While you are correct, I still think it wise (or at least convenient for the user) to have the Bravura font files that were used to generate the metadata and glyphnames.json files. And, yes, it's technically a _SMuFL_-only thing, but I'm still inclined to think that it makes sense to either keep all the latest SMuFL/Bravura files in the repository, or none of them and require the user to go get them. Even though the SMuFL repository is listed under w3c, it's really Daniel Spreadbury of Steinberg that remains the head of its development, which means that if anything changes to SMuFL, Bravura will follow suit. If we're going to make any SMuFL file available here, why not the font files most closely associated to it?

Additionally, I just remembered that glyphnames.json isn't technically complete. There are many glyphs that aren't listed there because they show up as OpenType alternates. Their unicode data is found in the metadata file, the most complete listing being Bravura's. It's not hard to extract that and add it to the list in smufldata.ily, so it should probably be done. Another reason, IMO, to keep Bravura and its files along for the ride.

**Pull request merged**
